# change to list chars of your dataset or use default vietnamese chars

vocab: 'aAÃ Ã€áº£áº¢Ã£ÃƒÃ¡Ãáº¡áº ÄƒÄ‚áº±áº°áº³áº²áºµáº´áº¯áº®áº·áº¶Ã¢Ã‚áº§áº¦áº©áº¨áº«áºªáº¥áº¤áº­áº¬bBcCdDÄ‘ÄeEÃ¨Ãˆáº»áººáº½áº¼Ã©Ã‰áº¹áº¸ÃªÃŠá»á»€á»ƒá»‚á»…á»„áº¿áº¾á»‡á»†fFgGhHiIÃ¬ÃŒá»‰á»ˆÄ©Ä¨Ã­Ãá»‹á»ŠjJkKlLmMnNoOÃ²Ã’á»á»ÃµÃ•Ã³Ã“á»á»ŒÃ´Ã”á»“á»’á»•á»”á»—á»–á»‘á»á»™á»˜Æ¡Æ á»á»œá»Ÿá»á»¡á» á»›á»šá»£á»¢pPqQrRsStTuUÃ¹Ã™á»§á»¦Å©Å¨ÃºÃšá»¥á»¤Æ°Æ¯á»«á»ªá»­á»¬á»¯á»®á»©á»¨á»±á»°vVwWxXyYá»³á»²á»·á»¶á»¹á»¸Ã½Ãá»µá»´zZ0123456789! "#$%&''()*Â±+Ã—,-./:;â‰¤â‰¥<=â‰ â‰ˆ>â†â†’â‡”?@[\]^_{|âŠ¥}~âˆ‘â€¦É£Â§Ï•Î¦Î¶Î´Î¾ğœ‘Î²Î±Î»â‹ŒÏ€Î·ÏƒÏ‰Ï…Î¸Î³Ï„Î©âˆ©âˆªâŠƒâŠ‚âŠ†Â«Â»Ã˜É›Ğ·É™âœ“â– â€¢â–â¢âˆ€ÂµÎ”âˆ‡âˆâˆˆâˆ‰âˆƒÎ½Ï†âˆ§Î“'

# cpu, cuda, cuda:0
device: cuda:0

model_type: repvgg
seq_model_type: seq2seq

seq_parameters:
    encoder_hidden: 256
    decoder_hidden: 256
    img_channel: 256
    decoder_embedded: 256
    dropout: 0.1

transformer_parameters:
    d_model: 256
    nhead: 8
    num_encoder_layers: 6
    num_decoder_layers: 6
    dim_feedforward: 2048
    max_seq_length: 1024
    pos_dropout: 0.1
    trans_dropout: 0.1

optimizer:
    pct_start: 0.1

trainer:
    print_every: 200
    valid_every: 10000
    # where to save our model for prediction
    export: ./weights/vietnamese_ocr.pth.tar
    checkpoint: ./checkpoint/transformerocr_checkpoint.pth
    log: ./train.log
    # null to disable compuate accuracy, or change to number of sample to enable validiation while training
    metrics: null
    batch_size: 70
    num_iters: 100000000

dataloader:
    num_workers: 16
    pin_memory: True
    
predictor:
    # disable or enable beamsearch while prediction, use beamsearch will be slower
    beamsearch: False

preprocess:
    width: 32
    height: 356

dataset:
    # name of your dataset